version: '3'
services:
  woroom-web:
    image: registry.ferumflex.com/ferumflex/woroom:latest
    networks:
      - backend
      - traefik_frontend
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.backend=woroom"
        - "traefik.frontend.rule=Host:woroom.network"
        - "traefik.docker.network=traefik_frontend"
        - "traefik.backend.loadbalancer.sticky=true"
        - "traefik.port=80"

networks:
  backend:
  traefik_frontend:
    external: true